In [2]:
import numpy as np
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [3]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [16]:
    >>> np.linspace(1, 100, num=5, endpoint=False)
print('for endpoin true===>  ',np.linspace(1,100,num=5,endpoint=True))
print('for endpoin false===>  ',np.linspace(1,100,num=5,endpoint=False))

for endpoin true===>   [  1.    25.75  50.5   75.25 100.  ]
for endpoin false===>   [ 1.  20.8 40.6 60.4 80.2]


In [5]:
    >>> np.linspace(2.0, 3.0, num=5)


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [12]:
np.linspace(1,100,num=5,retstep=False)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [16]:
#use of join in python
test = {'2', '1', '3'}
s = '==> '
print(s.join(test))

test = {'Python', 'Java', 'Ruby'}
s = '->->'
print(s.join(test))

3==> 1==> 2
Ruby->->Java->->Python
