In [1]:
import numpy as np
a=np.zeros(6)
a.dtype

dtype('float64')

In [4]:
a=np.zeros(5,dtype=np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [5]:
# astype is use for change datatype
a=np.zeros(5)
a.astype(int)

array([0, 0, 0, 0, 0])

In [6]:
a=np.zeros(5)
np.float64(a)

array([0., 0., 0., 0., 0.])