# sliceing a[start:end:step]
# sliceing in two dimensional array a[start:end:stop,start:end:stop]


In [1]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a[1:,1:]

array([[4],
       [6]])

In [2]:
a=np.array([[1,2,8],[3,4,9],[5,6,10]])
a[::,::2]#STEP OCOUR IN COLUMN

array([[ 1,  8],
       [ 3,  9],
       [ 5, 10]])

THTREE DIMENSIONAL ARRAY SLICEING
a[start:end:step,start:end:step,start:end:step]

In [4]:
b=[[[1,2,3],
    [4,5,6],
    [7,8,9]],
   
   [[10,11,12],
    [13,14,15],
    [16,17,18]]]
c=np.array(b)
c[:,:,:1]
#c[0]=: means we want two two dimensional matrix


array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]]])

In [5]:
c[:,1:,::2]

array([[[ 4,  6],
        [ 7,  9]],

       [[13, 15],
        [16, 18]]])