In [3]:
import numpy as np
a=np.arange(30,40)
a[[3,4,8]]

array([33, 34, 38])

In [4]:
# second method create a index
index=np.array([5,3,7])
a[index]

array([35, 33, 37])

In [10]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
#we wand to get 2, and 8
#b[[row,row],[column,column]]
print(b[[0,2],[1,1]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 8]


In [11]:
#this is called boolian oparation
b[b>5]*2


array([12, 14, 16, 18])