In [1]:
# it is is arry with diffrent size of array
# broadcusting rule:
#     1:dimension of two element is same
#         2:SIZE OF ONE DIMENSION SHOULD BE 1

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
pri
b=np.array([[10,20,30]])
a+b

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

|name||age|
|----||----|
|rakib||20|
| sakib al hasan   ||40   || sakib al hasan   ||40   |

In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,20,30]])
print('shape of a :',a.shape)
print('size of a :',a.size)
print('shape of b :',b.shape)
print('size of b :',b.size)
print('a+b result :\n',a+b)
# if both column is same then broadcasting is possible shape should be (1,n)

shape of a : (3, 3)
size of a : 9
shape of b : (1, 3)
size of b : 3
a+b result :
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
