In [8]:
import numpy as np 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a.fletten \n',a.flatten())
print('a.fletten order='F' \n',a.flatten(order='F'))
#you can also use order=k or a

a.fletten 
 [1 2 3 4 5 6 7 8 9]
a.fletten order= 
 [1 4 7 2 5 8 3 6 9]


|flatten||raval|
|-------||-----|
|it only give cope||it only give the view of the array or refarence|

In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a.raval() \n',a.ravel())
print(np.ravel(a,order="F"))#it order column wise

a.raval() 
 [1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
