In [3]:
import numpy as np
array1=np.arange(1,11).reshape(5,2)
print(np.transpose(array1))
print('shape of array1 is : ',array1.shape)
print('shape of arry1 after transpose :',np.transpose(array1).shape)
#transpose does not work in 1 dimensional array

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
shape of array1 is :  (5, 2)
shape of arry1 after transpose : (2, 5)


In [8]:
#3d array
import numpy as np
array2=np.array([
    [
  [1,2,3],
  [4,5,6],
  [7,8,9]
],
  [
    [10,11,12],
    [13,14,15],
    [16,17,18]
    ]
])
print(np.transpose(array2))
print('array 2 shape is :',array2.shape)
print('array 2 shape after: ',np.transpose(array2).shape)

[[[ 1 10]
  [ 4 13]
  [ 7 16]]

 [[ 2 11]
  [ 5 14]
  [ 8 17]]

 [[ 3 12]
  [ 6 15]
  [ 9 18]]]
array 2 shape is : (2, 3, 3)
array 2 shape after:  (3, 3, 2)


In [10]:
import numpy as np
array3=np.arange(1,25).reshape(2,3,4)
# here 2=0 position,3=1 position,4=2 position
print(np.transpose(array3,(1,2,0)))# 3 2d arry,4 row,2 column
#for 2d arry axes is (0,1),(1,0)
#for 3d array axis is 0,1,2
#rule   :np.ranspose(string,axis=(0,1))

[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]


In [12]:
#shortcut of transpose 
a=np.arange(1,10).reshape(3,3)
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

   # swapaxes(array,axes1,axes2)

In [16]:
a=np.array([[1,2,3]])
print(np.swapaxes(a,0,1))

[[1]
 [2]
 [3]]


In [18]:
#swap axis in three dimension
array2=np.array([
    [
  [1,2,3],
  [4,5,6],
  [7,8,9]
],
  [
    [10,11,12],
    [13,14,15],
    [16,17,18]
    ]
])
print(np.swapaxes(array2,2,1))#here we want to swap row and column
#for 3d arry 0=nuber of 2d matrix, 1=no of row ,2=no of column

[[[ 1  4  7]
  [ 2  5  8]
  [ 3  6  9]]

 [[10 13 16]
  [11 14 17]
  [12 15 18]]]
