In [5]:
import numpy as np
# help(np.concatenate)
a=np.arange(1,6)
b=np.arange(5)
print('concatenate :',np.concatenate((a,b)))#use double brakect
c=np.zeros(10)
print(np.concatenate((a,b),out=c))#out means output
print('data stored in c is :',c)


concatenate : [1 2 3 4 5 0 1 2 3 4]
[1. 2. 3. 4. 5. 0. 1. 2. 3. 4.]
data stored in c is : [1. 2. 3. 4. 5. 0. 1. 2. 3. 4.]


In [12]:
c=np.array([[1,2],[3,4]])
d=np.array([[8,9]])
print('concatning (c,d) :\n ',np.concatenate((c,d)))
print('concatning with axis 1 :',np.concatenate((c,d.T),axis=1))#axis 1 means columnwise

concatning (c,d) :
  [[1 2]
 [3 4]
 [8 9]]
concatning with axis 1 : [[1 2 8]
 [3 4 9]]


#                                         vstack function 
##    vstack function add array vertically
##   it behave 1d arry diffrent type and 3d,2d,4d... arry diffrent type
##   axis=0 


In [15]:
import numpy as np
# help(np.concatenate)
a=np.arange(1,6)
b=np.arange(5)
print('using vstack :\n\n',np.vstack((a,b)))#use double brakect
#it will give two dimensional array

# ----------------------------------for 2d array----------------------------------
c=np.array([[1,2],[3,4]])
d=np.array([[8,9]])
print('v stack (c,d) :\n\n ',np.vstack((c,d)))


using vstack :

 [[1 2 3 4 5]
 [0 1 2 3 4]]
v stack (c,d) :

  [[1 2]
 [3 4]
 [8 9]]


#                                         hstack function 
##    hstack function add array horizontally
##   it behave 1d arry diffrent type and 3d,2d,4d... arry diffrent type
##   axis=1 


In [18]:
import numpy as np
# help(np.concatenate)
a=np.arange(1,6)
b=np.arange(5)
print('using hstack :\n\n',np.hstack((a,b)))#use double brakect


# ----------------------------------for 2d array----------------------------------
c=np.array([[1,2],[3,4]])
d=np.array([[8,9]])
print('hstack (c,d.T) :\n\n ',np.hstack((c,d.T)))


using hstack :

 [1 2 3 4 5 0 1 2 3 4]
v stack (c,d.T) :

  [[1 2 8]
 [3 4 9]]


# -----------------------------split,hsplit,vsplit-----------------------------
###                   split(array,number of subsection,axis=)

In [25]:
e=np.arange(1,10)
print(np.split(e,3))
#reshape and arrange function work at same way
#we can also call avobe method as v split method because axis =0
print('hsplit in one dimension :',np.hsplit(e,3))


f=np.arange(1,13).reshape(2,6)
print('hsplit in two dimensional array :\n\n',np.hsplit(f,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
hsplit in one dimension : [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
hsplit in two dimensional array :

 [array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
