### insert(array,obj,value,axis=NONE)
### obj is one type of indexing

In [4]:
import numpy as np
a=np.arange(1,10)
print(np.insert(a,3,50.3))#position 3,and it convert a floating value in a integer valueprint(np.insert(a,3,50.3))
print(np.insert(a,(0,4),50.3))#position 3,and it convert a floating value in a integer valueprint(np.insert(a,3,50.3))

[ 1  2  3 50  4  5  6  7  8  9]
[50  1  2  3  4 50  5  6  7  8  9]


In [10]:
#insert for 2d array
b=np.array([[1,2],[3,4]])
print(np.insert(b,2,20))#this make array flatten in one dimensional arrey so use axis to get 2d
print(np.insert(b,2,20,axis=0))#look this this is totally brodcasting
print(np.insert(b,2,[5,80],axis=0))
print(np.insert(b,2,[5,80],axis=1))


[ 1  2 20  3  4]
[[ 1  2]
 [ 3  4]
 [20 20]]
[[ 1  2]
 [ 3  4]
 [ 5 80]]
[[ 1  2  5]
 [ 3  4 80]]


### diffrent between insert and append is append add value at the last of string

# append(array,value ,axis)

In [18]:
b=np.array([[1,2],[3,4]])
print(np.append(b,20))#this make array flatten in one dimensional arrey so use axis to get 2d
print(np.append(b,20))#look this this is totally brodcasting
print(np.append(b,[[5,80]],axis=0))#without axis it can't be give 2d array
#use nasted value otherwise it make error
print(np.append(b,[[5,80]],axis=1))
print(np.append(b,5,axis=0))#error
"""
it make error because :
   1 2|5 80|
   3 5
   that is not possible
"""

[ 1  2  3  4 20]
[ 1  2  3  4 20]
[[ 1  2]
 [ 3  4]
 [ 5 80]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

# delete(array,obj /index,axis)

In [19]:
b=np.array([[1,2],[3,4]])
np.delete(b,0)

array([2, 3, 4])

In [20]:
b=np.array([[1,2],[3,4]])
np.delete(b,0,axis=0)

array([[3, 4]])

In [21]:
b=np.array([[1,2],[3,4]])
np.delete(b,0,axis=1)

array([[2],
       [4]])