In [1]:
import numpy as np
a=np.matrix('1 2;3 4')
print(a)

[[1 2]
 [3 4]]


In [2]:
b=np.matrix([[10,20],[30,40]])
print(b)

[[10 20]
 [30 40]]


In [3]:
a+b

matrix([[11, 22],
        [33, 44]])

In [4]:
a.dot(b)

matrix([[ 70, 100],
        [150, 220]])

In [5]:
a.T

matrix([[1, 3],
        [2, 4]])

In [ ]:
# matrix object is always 2d
#matrix multipication we use a.dot(b) not a*b