In [4]:
import numpy as np
# help(np.array)
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([1,2,3],'complex')
b

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
print(b)

[1.+0.j 2.+0.j 3.+0.j]


In [8]:
# remember give two brakate
c=np.array([[1,2,3],[4,5,2]])
print(c)

[[1 2 3]
 [4 5 2]]
